"""Agrega campo id_instructor_aprobador a Solicitud

Revision ID: 5df38af83b36
Revises: e6c738aafdae
Create Date: 2025-05-28 09:17:39.625098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5df38af83b36'
down_revision = 'e6c738aafdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONFIGURACION',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_config'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('FICHAS',
    sa.Column('id_ficha', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_ficha')
    )
    op.create_table('TIPOS_SALIDA',
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('requiere_reingreso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo')
    )
    op.create_table('USUARIOS',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('aprendiz', 'instructor', 'administrativo', 'porteria', 'admin', name='rolesenum'), nullable=False),
    sa.Column('id_ficha', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_ficha'], ['FICHAS.id_ficha'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('SOLICITUDES',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_aprendiz', sa.Integer(), nullable=False),
    sa.Column('id_tipo_salida', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('hora_salida_estimada', sa.Time(), nullable=False),
    sa.Column('hora_reingreso_estimada', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', 'completada', name='estadosolicitud'), nullable=False),
    sa.Column('id_instructor_aprobador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['USUARIOS.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_instructor_aprobador'], ['USUARIOS.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_tipo_salida'], ['TIPOS_SALIDA.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('AUDITORIA_GENERAL',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['SOLICITUDES.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index('fk_solicitudes_tipos_idx')
        batch_op.drop_index('fk_solicitudes_usuarios_idx')

    op.drop_table('solicitudes')
    with op.batch_alter_table('auditoria_general', schema=None) as batch_op:
        batch_op.drop_index('fk_auditoria_solicitudes_idx')
        batch_op.drop_index('fk_auditoria_usuarios_idx')

    op.drop_table('auditoria_general')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('documento')
        batch_op.drop_index('email')
        batch_op.drop_index('fk_usuarios_fichas_idx')

    op.drop_table('usuarios')
    op.drop_table('fichas')
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_index('clave')

    op.drop_table('configuracion')
    op.drop_table('tipos_salida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_salida',
    sa.Column('id_tipo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False, comment='Ej: Temporal, Definitiva, Médica'),
    sa.Column('requiere_reingreso', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='1=Sí, 0=No'),
    sa.PrimaryKeyConstraint('id_tipo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('configuracion',
    sa.Column('id_config', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', mysql.VARCHAR(length=50), nullable=False, comment='Ej: max_horas_reingreso'),
    sa.Column('valor', mysql.TEXT(), nullable=False, comment='Valor en formato JSON'),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_config'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.create_index('clave', ['clave'], unique=True)

    op.create_table('fichas',
    sa.Column('id_ficha', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False, comment='Ej: Ficha 2023-A'),
    sa.Column('descripcion', mysql.TEXT(), nullable=True, comment='Detalles del grupo/formación'),
    sa.PrimaryKeyConstraint('id_ficha'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('documento', mysql.VARCHAR(length=20), nullable=False, comment='DNI/Cédula'),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False, comment='Encriptado con bcrypt'),
    sa.Column('rol', mysql.ENUM('aprendiz', 'instructor', 'administrativo', 'porteria', 'admin'), nullable=False),
    sa.Column('id_ficha', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Solo para aprendices'),
    sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ultimo_login', mysql.DATETIME(), nullable=True),
    sa.Column('validado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ficha'], ['fichas.id_ficha'], name='fk_usuarios_fichas', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('fk_usuarios_fichas_idx', ['id_ficha'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('documento', ['documento'], unique=True)

    op.create_table('auditoria_general',
    sa.Column('id_log', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Usuario que realizó la acción'),
    sa.Column('id_solicitud', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', mysql.VARCHAR(length=50), nullable=False, comment='Ej: solicitud_creada, aprobada, rechazada'),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('detalles', mysql.TEXT(), nullable=True, comment='JSON con datos adicionales'),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id_solicitud'], name='fk_auditoria_solicitudes', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_auditoria_usuarios', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_log'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auditoria_general', schema=None) as batch_op:
        batch_op.create_index('fk_auditoria_usuarios_idx', ['id_usuario'], unique=False)
        batch_op.create_index('fk_auditoria_solicitudes_idx', ['id_solicitud'], unique=False)

    op.create_table('solicitudes',
    sa.Column('id_solicitud', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aprendiz', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Usuario con rol aprendiz'),
    sa.Column('id_tipo_salida', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hora_salida_estimada', mysql.TIME(), nullable=False),
    sa.Column('hora_reingreso_estimada', mysql.TIME(), nullable=True, comment='Solo si el tipo lo requiere'),
    sa.Column('hora_salida_exacta', mysql.TIME(), nullable=True, comment='Registrada por portería'),
    sa.Column('hora_reingreso_exacta', mysql.TIME(), nullable=True),
    sa.Column('motivo', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'aprobada', 'rechazada', 'completada'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('id_instructor_aprobador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_administrativo_validador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_porteria_registrador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_aprendiz'], ['usuarios.id_usuario'], name='fk_solicitudes_aprendices', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_salida'], ['tipos_salida.id_tipo'], name='fk_solicitudes_tipos', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_solicitud'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index('fk_solicitudes_usuarios_idx', ['id_aprendiz'], unique=False)
        batch_op.create_index('fk_solicitudes_tipos_idx', ['id_tipo_salida'], unique=False)

    op.drop_table('AUDITORIA_GENERAL')
    op.drop_table('SOLICITUDES')
    op.drop_table('USUARIOS')
    op.drop_table('TIPOS_SALIDA')
    op.drop_table('FICHAS')
    op.drop_table('CONFIGURACION')
    # ### end Alembic commands ###
